# Generated by qwenpaw-protocol. Do not edit.

PROTOCOL_VERSION = 3

APP_PROTOCOL_REQUEST_METHODS = (
    "initialize",
    "thread/start",
    "thread/resume",
    "thread/archive",
    "thread/list",
    "thread/read",
    "turn/start",
    "turn/interrupt",
    "tool/approval/respond",
    "model/list",
    "config/read",
    "config/write",
    "workspace/list",
    "workspace/read",
    "mcp/list",
    "mcp/oauth/start",
    "mcp/oauth/status",
    "mcp/oauth/revoke",
)

APP_PROTOCOL_SERVER_NOTIFICATION_METHODS = (
    "thread/started",
    "turn/started",
    "item/started",
    "item/agentMessage/delta",
    "item/completed",
    "tool/approval/requested",
    "tool/approval/resolved",
    "turn/completed",
)
