fn main() {
    // The Tauri bootstrap is generated by `build:tauri-bootstrap`. Raw
    // `cargo build` is also used by the packaging and local replacement
    // flows, so make the generated frontend an explicit build input rather
    // than silently reusing a binary that embedded an older (or empty)
    // bootstrap directory.
    println!("cargo:rerun-if-changed=../dist-tauri");
    tauri_build::build()
}
