// Generated by qwenpaw-protocol. Do not edit.

export type ClientInfo = { name: string, version: string, title: string | null, };

export type InitializeParams = { clientInfo: ClientInfo, };

export type ServerInfo = { name: string, version: string, };

export type InitializeResponse = { protocolVersion: number, serverInfo: ServerInfo, };

export type ThreadStatus = "idle" | "active" | "error";

export type Thread = { id: string, model: string, workspaceRoot: string | null, status: ThreadStatus, archived: boolean, createdAt: number, updatedAt: number, };

export type ThreadStartParams = { model: string | null, workspaceRoot: string | null, };

export type ThreadStartResponse = { thread: Thread, };

export type ThreadResumeParams = { threadId: string, };

export type ThreadResumeResponse = { thread: Thread, };

export type ThreadArchiveParams = { threadId: string, };

export type ThreadArchiveResponse = { thread: Thread, };

export type ThreadListParams = { cursor: string | null, limit: number | null, includeArchived: boolean, };

export type ThreadListResponse = { data: Array<Thread>, nextCursor: string | null, };

export type ThreadReadParams = { threadId: string, };

export type Item = { "type": "userMessage", id: string, text: string, } | { "type": "agentMessage", id: string, text: string, } | { "type": "toolCall", id: string, callId: string, name: string, arguments: string, } | { "type": "toolResult", id: string, callId: string, content: string, isError: boolean, };

export type ErrorInfo = { message: string, };

export type TurnStatus = "inProgress" | "completed" | "interrupted" | "failed";

export type Turn = { id: string, threadId: string, status: TurnStatus, items: Array<Item>, error: ErrorInfo | null, };

export type ThreadReadResponse = { thread: Thread, turns: Array<Turn>, };

export type UserInput = { "type": "text", text: string, } | { "type": "fileReference", path: string, startLine: number | null, endLine: number | null, };

export type TurnStartParams = { threadId: string, input: Array<UserInput>, };

export type TurnStartResponse = { turn: Turn, };

export type TurnInterruptParams = { threadId: string, turnId: string, };

export type TurnInterruptResponse = { accepted: boolean, };

export type ApprovalDecision = "approved" | "denied";

export type ToolApprovalRespondParams = { approvalId: string, decision: ApprovalDecision, };

export type ToolApprovalRespondResponse = { accepted: boolean, };

export type ModelListParams = Record<string, never>;

export type ModelInfo = { id: string, displayName: string, isDefault: boolean, };

export type ModelListResponse = { data: Array<ModelInfo>, };

export type ConfigReadParams = Record<string, never>;

export type ConfigReadResponse = { config: CoreConfig, };

export type ConfigWriteParams = { baseUrl: string | null, defaultModel: string | null, };

export type ConfigWriteResponse = { config: CoreConfig, };

export type CoreConfig = { baseUrl: string, defaultModel: string, apiKeyConfigured: boolean, };

export type WorkspaceListParams = Record<string, never>;

export type WorkspaceListResponse = { data: Array<WorkspaceInfo>, };

export type WorkspaceReadParams = { root: string, };

export type WorkspaceReadResponse = { workspace: WorkspaceInfo, };

export type WorkspaceInfo = { root: string, threadCount: number, archivedThreadCount: number, updatedAt: number, };

export type McpListParams = Record<string, never>;

export type McpListResponse = { data: Array<McpClientInfo>, };

export type McpClientInfo = { serverId: string, name: string, description: string, enabled: boolean, transport: string, url: string, oauthStatus: McpOAuthStatus | null, };

export type McpOAuthStatus = { authorized: boolean, expiresAt: number, scope: string, clientId: string, };

export type McpOAuthStartParams = { serverId: string, url: string | null, scope: string | null, clientId: string | null, authorizationEndpoint: string | null, tokenEndpoint: string | null, };

export type McpOAuthStartResponse = { authorizationUrl: string, sessionId: string, };

export type McpOAuthStatusParams = { serverId: string, };

export type McpOAuthStatusResponse = { status: McpOAuthStatus, };

export type McpOAuthRevokeParams = { serverId: string, };

export type McpOAuthRevokeResponse = { revoked: boolean, };

export type ThreadStartedNotification = { thread: Thread, };

export type TurnStartedNotification = { turn: Turn, };

export type ItemStartedNotification = { threadId: string, turnId: string, item: Item, };

export type AgentMessageDeltaNotification = { threadId: string, turnId: string, itemId: string, delta: string, };

export type ItemCompletedNotification = { threadId: string, turnId: string, item: Item, };

export type TurnCompletedNotification = { turn: Turn, };

export type ToolApprovalRequestedNotification = { threadId: string, turnId: string, approvalId: string, callId: string, toolName: string, arguments: string, workspaceRoot: string, };

export type ToolApprovalResolvedNotification = { threadId: string, turnId: string, approvalId: string, decision: ApprovalDecision, };

export interface AppProtocolRequests {
  readonly "initialize": { readonly params: InitializeParams; readonly result: InitializeResponse };
  readonly "thread/start": { readonly params: ThreadStartParams; readonly result: ThreadStartResponse };
  readonly "thread/resume": { readonly params: ThreadResumeParams; readonly result: ThreadResumeResponse };
  readonly "thread/archive": { readonly params: ThreadArchiveParams; readonly result: ThreadArchiveResponse };
  readonly "thread/list": { readonly params: ThreadListParams; readonly result: ThreadListResponse };
  readonly "thread/read": { readonly params: ThreadReadParams; readonly result: ThreadReadResponse };
  readonly "turn/start": { readonly params: TurnStartParams; readonly result: TurnStartResponse };
  readonly "turn/interrupt": { readonly params: TurnInterruptParams; readonly result: TurnInterruptResponse };
  readonly "tool/approval/respond": { readonly params: ToolApprovalRespondParams; readonly result: ToolApprovalRespondResponse };
  readonly "model/list": { readonly params: ModelListParams; readonly result: ModelListResponse };
  readonly "config/read": { readonly params: ConfigReadParams; readonly result: ConfigReadResponse };
  readonly "config/write": { readonly params: ConfigWriteParams; readonly result: ConfigWriteResponse };
  readonly "workspace/list": { readonly params: WorkspaceListParams; readonly result: WorkspaceListResponse };
  readonly "workspace/read": { readonly params: WorkspaceReadParams; readonly result: WorkspaceReadResponse };
  readonly "mcp/list": { readonly params: McpListParams; readonly result: McpListResponse };
  readonly "mcp/oauth/start": { readonly params: McpOAuthStartParams; readonly result: McpOAuthStartResponse };
  readonly "mcp/oauth/status": { readonly params: McpOAuthStatusParams; readonly result: McpOAuthStatusResponse };
  readonly "mcp/oauth/revoke": { readonly params: McpOAuthRevokeParams; readonly result: McpOAuthRevokeResponse };
}

export interface AppProtocolServerNotifications {
  readonly "thread/started": ThreadStartedNotification;
  readonly "turn/started": TurnStartedNotification;
  readonly "item/started": ItemStartedNotification;
  readonly "item/agentMessage/delta": AgentMessageDeltaNotification;
  readonly "item/completed": ItemCompletedNotification;
  readonly "tool/approval/requested": ToolApprovalRequestedNotification;
  readonly "tool/approval/resolved": ToolApprovalResolvedNotification;
  readonly "turn/completed": TurnCompletedNotification;
}

export const PROTOCOL_VERSION = 3 as const;


export const APP_PROTOCOL_REQUEST_METHODS = [
  "initialize",
  "thread/start",
  "thread/resume",
  "thread/archive",
  "thread/list",
  "thread/read",
  "turn/start",
  "turn/interrupt",
  "tool/approval/respond",
  "model/list",
  "config/read",
  "config/write",
  "workspace/list",
  "workspace/read",
  "mcp/list",
  "mcp/oauth/start",
  "mcp/oauth/status",
  "mcp/oauth/revoke",
] as const;

export const APP_PROTOCOL_SERVER_NOTIFICATION_METHODS = [
  "thread/started",
  "turn/started",
  "item/started",
  "item/agentMessage/delta",
  "item/completed",
  "tool/approval/requested",
  "tool/approval/resolved",
  "turn/completed",
] as const;